# Generated by Django 5.2.3 on 2025-10-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data informada pelo usuário no upload, usada para filtros.', verbose_name='Data de Referência (Arquivo)')),
                ('data_upload_sistema', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload no Sistema')),
                ('spx_tracking_number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='SPX Tracking Number')),
                ('scanned_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scanned Status')),
                ('expedite_tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expedite Tag')),
                ('final_status', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Final Status')),
                ('sort_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sort Code')),
                ('next_step_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Next Step Action')),
                ('on_hold_times', models.IntegerField(blank=True, null=True, verbose_name='On Hold Times')),
                ('count_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Count Type')),
                ('expected', models.CharField(blank=True, max_length=10, null=True, verbose_name='Expected')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operator')),
                ('aging_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aging Time')),
                ('scanned_time', models.DateTimeField(blank=True, null=True, verbose_name='Scanned Time')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Upload')),
            ],
            options={
                'verbose_name': 'Item Parcel',
                'verbose_name_plural': 'Itens Parcel',
            },
        ),
    ]
