# Generated by Django 5.2.3 on 2025-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_sweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='on_hold_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='On Hold Times'),
        ),
    ]
