# Generated by Django 5.2.3 on 2025-10-10 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_sweeper', '0002_alter_parcel_on_hold_times'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='spx_tracking_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='SPX Tracking Number'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.UniqueConstraint(fields=('spx_tracking_number', 'data_referencia'), name='unique_parcel_day'),
        ),
    ]
