# Generated by Django 5.2.3 on 2025-10-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apresentacao', models.DateField(unique=True, verbose_name='Data da Apresentação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
                'ordering': ['-data_apresentacao'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Tópico')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='apresentacao.apresentacao', verbose_name='Apresentação Relacionada')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['ordem', 'titulo'],
                'unique_together': {('apresentacao', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Card')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apresentado')),
                ('valor_formatado', models.CharField(help_text="Ex: '1.250' ou 'R$ 50k'", max_length=50, verbose_name='Valor (Exibição)')),
                ('cor', models.CharField(choices=[('primary', 'Azul (Primary)'), ('secondary', 'Cinza (Secondary)'), ('success', 'Verde (Success)'), ('danger', 'Vermelho (Danger)'), ('warning', 'Amarelo/Laranja (Warning)'), ('info', 'Ciano (Info)'), ('dark', 'Preto (Dark)')], default='primary', max_length=20, verbose_name='Cor do Card (Bootstrap)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='apresentacao.topico', verbose_name='Tópico Relacionado')),
            ],
            options={
                'verbose_name': 'Card de Apresentação',
                'verbose_name_plural': 'Cards de Apresentação',
                'ordering': ['topico', 'ordem', 'titulo'],
            },
        ),
    ]
