# Generated by Django 5.2.3 on 2025-10-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apresentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apresentado (Numérico)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='valor_formatado',
            field=models.CharField(help_text="Ex: '1.250', 'R$ 50k' ou '98.5%'", max_length=50, verbose_name='Valor (Exibição)'),
        ),
    ]
