# Generated by Django 5.2.3 on 2025-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apresentacao', '0002_alter_card_valor_alter_card_valor_formatado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='A data para a qual os dados estão sendo inseridos.', unique=True, verbose_name='Data de Referência')),
                ('total_rotas', models.IntegerField(default=0, verbose_name='Total de Rotas')),
                ('total_pacotes_iniciados', models.IntegerField(default=0, verbose_name='Total de Pacotes Iniciados')),
                ('total_pacotes_finalizados', models.IntegerField(default=0, verbose_name='Total de Pacotes Finalizados')),
                ('total_pacotes_escaneados', models.IntegerField(default=0, verbose_name='Total de Pacotes Escaneados')),
                ('total_missorted', models.IntegerField(default=0, verbose_name='Total de Missorted')),
                ('total_missing_expedicao', models.IntegerField(default=0, verbose_name='Total de Missing Expedição')),
                ('total_onhold', models.IntegerField(default=0, verbose_name='Total Onhold')),
                ('onhold_devolvidos', models.IntegerField(default=0, verbose_name='Onhold Devolvidos')),
                ('onhold_devolver', models.IntegerField(default=0, verbose_name='Onhold Devolver')),
                ('volumosos_no_hub', models.IntegerField(default=0, verbose_name='Volumosos No HUB')),
                ('pnr', models.IntegerField(default=0, verbose_name='PNR')),
                ('backlog_parcel', models.IntegerField(default=0, verbose_name='Backlog Parcel')),
                ('pedidos_roteirizar_pool', models.IntegerField(default=0, verbose_name='Pedidos Roteirizar Pool')),
                ('total_reversa', models.IntegerField(default=0, verbose_name='Total Reversa')),
                ('missing_parcel', models.IntegerField(default=0, verbose_name='Missing Parcel')),
                ('avaria_soc', models.IntegerField(default=0, verbose_name='Avaria SOC')),
                ('avaria_hub', models.IntegerField(default=0, verbose_name='Avaria HUB')),
                ('backlog_agarrado_dias', models.IntegerField(default=0, verbose_name='Backlog Agarrado no HUB - Vários Dias')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dado Diário KPI',
                'verbose_name_plural': 'Dados Diários KPI',
                'ordering': ['-data'],
            },
        ),
    ]
