# Generated by Django 5.2.3 on 2025-10-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apresentacao', '0003_dadosdiarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosDiarios',
        ),
        migrations.AlterModelOptions(
            name='apresentacao',
            options={'ordering': ['-data_apresentacao'], 'verbose_name': 'Apresentação'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['topico', 'ordem'], 'verbose_name': 'Card/KPI'},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['apresentacao', 'ordem'], 'verbose_name': 'Tópico'},
        ),
        migrations.AlterUniqueTogether(
            name='topico',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Registro'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cor',
            field=models.CharField(choices=[('primary', 'Azul (Info)'), ('success', 'Verde (OK)'), ('danger', 'Vermelho (Crítico)'), ('warning', 'Amarelo (Alerta)'), ('info', 'Ciano (Detalhe)'), ('secondary', 'Cinza')], default='primary', max_length=10, verbose_name='Cor de Destaque'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='card',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título do Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='apresentacao.topico', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='card',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Numérico Real'),
        ),
        migrations.AlterField(
            model_name='card',
            name='valor_formatado',
            field=models.CharField(max_length=50, verbose_name='Valor para Exibição (Ex: R$ 50k / 98.5%)'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='apresentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='apresentacao.apresentacao', verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('topico', 'ordem')},
        ),
    ]
