# Generated by Django 5.2.3 on 2025-10-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedicaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='expedicao/uploads/')),
                ('data_referencia', models.DateField(verbose_name='Data de Envio do Lote (Filtro)')),
                ('nome_original', models.CharField(editable=False, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Upload')),
                ('num_registros', models.IntegerField(blank=True, null=True, verbose_name='Nº Registros')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
            ],
        ),
    ]
