# Generated by Django 5.2.3 on 2025-10-17 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedicao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedicaoarquivo',
            options={'verbose_name': 'Arquivo de Expedição', 'verbose_name_plural': 'Arquivos de Expedição'},
        ),
        migrations.RemoveField(
            model_name='expedicaoarquivo',
            name='enviado_em',
        ),
        migrations.RemoveField(
            model_name='expedicaoarquivo',
            name='nome_original',
        ),
        migrations.AddField(
            model_name='expedicaoarquivo',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expedicaoarquivo',
            name='arquivo',
            field=models.FileField(upload_to='expedicoes/', verbose_name='Arquivo CSV'),
        ),
        migrations.AlterField(
            model_name='expedicaoarquivo',
            name='data_referencia',
            field=models.DateField(verbose_name='Data de Referência'),
        ),
        migrations.AlterField(
            model_name='expedicaoarquivo',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expedicaoarquivo',
            name='num_registros',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RegistroExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_to', models.CharField(max_length=50, verbose_name='AT/TO')),
                ('corridor_cage', models.CharField(max_length=50, verbose_name='Corredor/Cage')),
                ('total_initial_orders', models.IntegerField(verbose_name='Iniciais')),
                ('total_final_orders', models.IntegerField(verbose_name='Finais')),
                ('total_scanned_orders', models.IntegerField(verbose_name='Escaneados')),
                ('missorted_orders', models.IntegerField(verbose_name='Missorted')),
                ('missing_orders', models.IntegerField(verbose_name='Missing')),
                ('validation_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início Validação')),
                ('validation_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim Validação')),
                ('validation_operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operador Validação')),
                ('revalidation_operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operador Revalidação')),
                ('revalidated_count', models.IntegerField(default=0, verbose_name='Revalidados')),
                ('at_to_validation_status', models.CharField(max_length=50, verbose_name='Status Validação')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('arquivo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='expedicao.expedicaoarquivo', verbose_name='Arquivo de Origem')),
            ],
            options={
                'verbose_name': 'Registro de Expedição',
                'verbose_name_plural': 'Registros de Expedição',
            },
        ),
    ]
