# Generated by Django 5.2.3 on 2025-10-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nº Rastreio')),
                ('action_type', models.CharField(choices=[('ADD', 'Adicionar à Collection Pool (Sobrescrever)'), ('REMOVE', 'Não Adicionar à Collection Pool (Ignorar)'), ('ROUTED', 'Marcar como Roteirizado (Sobrescrever)')], max_length=10, verbose_name='Tipo de Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Ação Manual',
                'verbose_name_plural': 'Registros de Ações Manuais',
            },
        ),
    ]
