# Generated by Django 5.2.3 on 2025-10-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(help_text='Data de referência para este registro de perda/avaria.', verbose_name='Data de Registro (Referência)')),
                ('spx_tracking_number', models.CharField(db_index=True, max_length=255, verbose_name='SPX Tracking Number')),
                ('final_status_avaria', models.CharField(choices=[('SOC_LOST', 'Soc - Lost'), ('SOC_DAMAGE', 'Soc - Damage'), ('HUB_LOST', 'HUB - Lost'), ('HUB_DAMAGE', 'HUB - Damage')], db_index=True, max_length=50, verbose_name='Status / Avaria')),
                ('data_ocorrencia_spx', models.DateField(blank=True, help_text='Data em que a avaria foi registrada no sistema SPX para o cliente.', null=True, verbose_name='Data Ocorrência SPX')),
                ('data_registro_sistema', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro no Sistema')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Registro')),
            ],
            options={
                'verbose_name': 'Perda ou Avaria',
                'verbose_name_plural': 'Perdas e Avarias',
                'constraints': [models.UniqueConstraint(fields=('spx_tracking_number', 'data_registro'), name='unique_lost_parcel_day')],
            },
        ),
    ]
