# Generated by Django 5.2.3 on 2025-10-07 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio_arquivo', models.DateField(verbose_name='Data de Envio do Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload no Sistema')),
                ('shipment_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Shipment Id')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zipcode')),
                ('destination_address', models.TextField(blank=True, null=True, verbose_name='Destination Address')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighborhood')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('cluster', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cluster')),
                ('address_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Type')),
                ('lh_trip', models.CharField(blank=True, max_length=50, null=True, verbose_name='LH Trip')),
                ('destination_hub', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination Hub')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('length_cm', models.FloatField(blank=True, null=True, verbose_name='Length(cm)')),
                ('width_cm', models.FloatField(blank=True, null=True, verbose_name='Width(cm)')),
                ('height_cm', models.FloatField(blank=True, null=True, verbose_name='Height(cm)')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Weight(kg)')),
                ('dimension_source_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimension Source Type')),
                ('to_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='TO ID')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Upload')),
            ],
            options={
                'verbose_name': 'Item do Collection Pool',
                'verbose_name_plural': 'Itens do Collection Pool',
                'unique_together': {('shipment_id', 'data_envio_arquivo')},
            },
        ),
    ]
