# Generated by Django 5.2.3 on 2025-10-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together=set(),
        ),
    ]
