# Generated by Django 5.2.7 on 2025-10-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('onhold', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onhold',
            options={'ordering': ['-data_envio', 'onhold_time'], 'verbose_name': 'Registro OnHold', 'verbose_name_plural': 'Registros OnHold'},
        ),
        migrations.AddField(
            model_name='onhold',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='onhold',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='onhold',
            name='manifest_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manifest Number'),
        ),
        migrations.AddField(
            model_name='onhold',
            name='parcel_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='onhold',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='onhold',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Largura (cm)'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Comprador'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comprador'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='hub_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hub', verbose_name='HUB do Upload'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='onhold_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo OnHold'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='onhold_time',
            field=models.DateField(blank=True, null=True, verbose_name='OnHold Data'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='shopee_order_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shopee Order SN'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='sls_tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SLS Tracking Number'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='sort_code_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sort Code Name'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='onhold',
            name='usuario_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Upload'),
        ),
    ]
