# Generated by Django 5.2.7 on 2025-10-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onhold', '0002_alter_onhold_options_onhold_height_onhold_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onhold',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name'),
        ),
    ]
