# Generated by Django 5.2.7 on 2025-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onhold', '0003_onhold_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onhold',
            name='data_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio/Referência'),
        ),
        migrations.AlterUniqueTogether(
            name='onhold',
            unique_together={('order_id', 'onhold_time')},
        ),
    ]
