# Generated by Django 5.2.3 on 2025-10-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onhold', '0004_alter_onhold_data_envio_alter_onhold_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onhold',
            unique_together=set(),
        ),
    ]
