# Generated by Django 5.2.3 on 2025-10-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('onhold', '0005_alter_onhold_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnholdInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de Envio/Referência')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID')),
                ('sls_tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='SLS Tracking Number')),
                ('shopee_order_sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shopee Order SN')),
                ('sort_code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sort Code Name')),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Comprador')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comprador')),
                ('buyer_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Comprador')),
                ('location_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location Type')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('driver_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driver Phone')),
                ('pick_up_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pick Up Time')),
                ('soc_received_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='SOC Received Time')),
                ('delivered_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivered Time')),
                ('onhold_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='OnHold Time')),
                ('onhold_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo OnHold')),
                ('reschedule_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reschedule Time')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('reject_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reject Remark')),
                ('manifest_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manifest Number')),
                ('order_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Account')),
                ('parcel_weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('sls_weight', models.FloatField(blank=True, null=True, verbose_name='SLS Weight (kg)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Comprimento (cm)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Largura (cm)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('original_asf', models.FloatField(blank=True, null=True, verbose_name='Original ASF')),
                ('rounding_asf', models.FloatField(blank=True, null=True, verbose_name='Rounding ASF')),
                ('cod_fee', models.FloatField(blank=True, null=True, verbose_name='COD Fee')),
                ('delivery_attempts', models.IntegerField(blank=True, null=True, verbose_name='Delivery Attempts')),
                ('bulky_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bulky Type')),
                ('sla_target_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='SLA Target Date')),
                ('time_to_sla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Time to SLA')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('pickup_station', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pickup Station')),
                ('destination_station', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination Station')),
                ('next_station', models.CharField(blank=True, max_length=150, null=True, verbose_name='Next Station')),
                ('current_station', models.CharField(blank=True, max_length=150, null=True, verbose_name='Current Station')),
                ('channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Channel')),
                ('previous_3pl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Previous 3PL')),
                ('next_3pl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Next 3PL')),
                ('shop_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop ID')),
                ('shop_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop Category')),
                ('inbound_3pl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inbound 3PL')),
                ('outbound_3pl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outbound 3PL')),
                ('hub_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hub', verbose_name='HUB do Upload')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Upload')),
            ],
            options={
                'verbose_name': 'Registro OnHold Inicial (Completo)',
                'verbose_name_plural': 'Registros OnHold Inicial (Completos)',
                'ordering': ['-data_envio'],
            },
        ),
    ]
