# Generated by Django 5.2.3 on 2025-10-20 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lista', models.CharField(choices=[('A', 'Lista A'), ('B', 'Lista B')], help_text='Indica se é a Lista A ou Lista B.', max_length=1)),
                ('arquivo_original', models.FileField(upload_to='conferencia_uploads/')),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='CARREGADO', help_text='Status do processamento do arquivo.', max_length=15)),
            ],
            options={
                'verbose_name': 'Upload de Conferência',
                'verbose_name_plural': 'Uploads de Conferência',
            },
        ),
        migrations.CreateModel(
            name='RegistroConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(db_index=True, max_length=255)),
                ('dados_extras', models.JSONField(blank=True, null=True)),
                ('lista_origem', models.CharField(choices=[('A', 'Lista A'), ('B', 'Lista B')], max_length=1)),
                ('status_conferencia', models.CharField(choices=[('SOMENTE_A', 'Somente na Lista A (Azul)'), ('SOMENTE_B', 'Somente na Lista B (Vermelho)'), ('PRESENTE', 'Presente em Ambas (Verde)'), ('PENDENTE', 'Aguardando Conferência')], default='PENDENTE', help_text='Resultado da comparação entre as listas.', max_length=15)),
            ],
            options={
                'verbose_name': 'Registro de Conferência',
                'verbose_name_plural': 'Registros de Conferência',
                'unique_together': {('codigo_item', 'lista_origem')},
            },
        ),
    ]
